export const formatTabName = (str: string) => {
  return str.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
};

export const getTableSchema = (tab: string) => {
  switch (tab) {
    case 'business-approvals': return ['Business Name', 'Owner', 'GST Number', 'Documents', 'Status'];
    case 'business-directory':
    case 'business-management': return ['Business Name', 'Category', 'City', 'Owner', 'Status'];
    case 'business-owners': return ['Owner Name', 'Contact Info', 'Business Type', 'Joined Date', 'Status'];
    case 'customers': return ['Customer Name', 'Email', 'Phone', 'Joined Date', 'Status'];
    case 'categories': return ['Category Name', 'Total Businesses', 'Active Listings', 'Trending', 'Status'];
    case 'locations': return ['City', 'State', 'Area Details', 'Pincode Coverage', 'Top Categories', 'Status'];
    case 'subscriptions': return ['Business Name', 'Plan', 'Amount', 'Expiry Date', 'Status'];
    case 'payments': return ['Transaction ID', 'Business', 'Amount', 'Date', 'Status'];
    case 'advertisements': return ['Ad Campaign', 'Business', 'Impressions', 'Clicks', 'Status'];
    case 'leads': return ['Lead Name', 'Business Assigned', 'Phone', 'Date', 'Status'];
    case 'reviews': return ['Business', 'Reviewer', 'Rating', 'Date', 'Status'];
    case 'support': return ['Ticket ID', 'Subject', 'User', 'Date', 'Status'];
    case 'notifications': return ['Title', 'Type', 'Target Audience', 'Date', 'Status'];
    case 'cms': return ['Page Title', 'Author', 'Last Updated', 'Views', 'Status'];
    case 'analytics':
    case 'reports': return ['Report Name', 'Generated By', 'Type', 'Date', 'Status'];
    case 'settings':
    case 'logs': return ['Action', 'User', 'IP Address', 'Date', 'Status'];
    default: return ['ID', 'Name', 'Description', 'Date', 'Status'];
  }
};

export const keyMap: Record<string, string> = {
  'Business Name': 'business_name',
  'Category': 'category',
  'Business Type': 'business_type',
  'Address': 'address',
  'City': 'city',
  'Pincode': 'pincode',
  'Business Phone': 'phone',
  'WhatsApp': 'whatsapp',
  'Website': 'website',
  'Description': 'description',
  'Owner': 'owner_name',
  'Owner Email': 'owner_email',
  'Owner Phone': 'owner_phone',
  'Approval Status': 'approval_status',
  'Status': 'is_verified',
  'Map URL': 'map_url',
  'Logo URL': 'logo_url',
  'Certificate URL': 'certificate_url',
  'Working Days': 'working_days',
  'Open Time': 'open_time',
  'Close Time': 'close_time',
  'Payment Methods': 'payment_methods',
  'Facebook URL': 'facebook_url',
  'Instagram URL': 'instagram_url',
  'Twitter URL': 'twitter_url',
  'LinkedIn URL': 'linkedin_url',
  'Owner Role': 'owner_role',
  'Owner Aadhar': 'owner_aadhar',
  'Owner Address': 'owner_address',
  'Display Name': 'display_name',
  'Sub Category': 'sub_category',
  'PAN Number': 'pan_number',
  'GSTIN Number': 'gstin_number',
  'Service Radius': 'service_radius',
  'Location Type': 'location_type',
  'Landline Number': 'landline_number',
  'Services Offered': 'services_offered',
  'Cover Banner URL': 'cover_banner_url',
  'GST Certificate URL': 'gst_certificate_url',
  'PAN Card URL': 'pan_card_doc_url',
  'Sunday Hours': 'sunday_hours',
  'Custom Slug': 'slug',
  'Meta Title': 'seo_title',
  'Meta Description': 'seo_description',
  'SEO Keywords': 'seo_keywords'
};

export const mapPayload = (editFormData: Record<string, any>) => {
  const payload: any = {};
  for (const [k, v] of Object.entries(editFormData)) {
    if (keyMap[k]) {
      if (k === 'Status') payload[keyMap[k]] = v === 'Verified';
      else payload[keyMap[k]] = v;
    } else {
      payload[k] = v;
    }
  }
  return payload;
};

export const groupLocations = (normalizedRows: any[]) => {
  const grouped = new Map<
    string,
    {
      id: number;
      City: string;
      State: string;
      'Area Details': Set<string>;
      'Pincode Coverage': Set<string>;
      'Top Categories': Set<string>;
      Status: string;
    }
  >();

  normalizedRows.forEach((row: any, index: number) => {
    const city = row.City || row.city || 'Unknown';
    const category = row.Category || row.category || 'N/A';
    const website = row.Website || row.website || '';
    const addressHint =
      website.includes('Trichy')
        ? website
        : city === 'Trichy'
          ? 'Cantonment, Thillai Nagar, Salai Road, KK Nagar, Woraiyur'
          : row['Area Details'] || row.address || 'Remote / global coverage';

    const pincodeHint =
      city === 'Trichy'
        ? ['620001', '620003', '620018', '620021']
        : ['N/A'];

    if (!grouped.has(city)) {
      grouped.set(city, {
        id: index + 1,
        City: city,
        State: city === 'Trichy' ? 'Tamil Nadu' : 'N/A',
        'Area Details': new Set<string>(),
        'Pincode Coverage': new Set<string>(),
        'Top Categories': new Set<string>(),
        Status: 'Active',
      });
    }

    const bucket = grouped.get(city)!;
    addressHint
      .split(',')
      .map((item: string) => item.trim())
      .filter(Boolean)
      .slice(0, 5)
      .forEach((item: string) => bucket['Area Details'].add(item));
    pincodeHint.forEach((item) => bucket['Pincode Coverage'].add(item));
    bucket['Top Categories'].add(category);
  });

  return Array.from(grouped.values()).map((row) => ({
    id: row.id,
    City: row.City,
    State: row.State,
    'Area Details': Array.from(row['Area Details']).join(', '),
    'Pincode Coverage': Array.from(row['Pincode Coverage']).join(', '),
    'Top Categories': Array.from(row['Top Categories']).join(', '),
    Status: row.Status,
  }));
};
